package de.innovationhub.prox.projectservice.project;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Optional;
import java.util.UUID;
import javax.transaction.Transactional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.AutoConfigureDataJpa;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.data.domain.AuditorAware;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

/**
 * These tests will test the controller mapping on /projects for basic CRUD functionality. As the
 * controllers are generated by Spring Data and an intense testing of them would end up as testing
 * the framework, the tests in this class should be considered as an integration test between API
 * and database.
 *
 * <p>The test class excludes the Security Filter Chain and mocks the web service Also it makes use
 * of the DataJpa test to rollback transactions after each test
 */
@SpringBootTest
@AutoConfigureMockMvc(addFilters = false)
@AutoConfigureDataJpa
@Transactional
class ProjectAPITest {
  private static final String PROJECTS_ROUTE = "/projects";
  private static final String PROJECTS_ID_ROUTE = "/projects/{id}";

  @Autowired MockMvc mockMvc;

  @Autowired ProjectRepository projectRepository;

  @MockBean AuditorAware<UUID> auditorAware;

  // Generating a User ID which is used for performing authorized requests that depend on the
  // requesting User ID
  // That User ID can be referenced from within the tests
  private static final UUID USER_ID = UUID.randomUUID();

  Project sampleProject =
      new Project(
          "Test Project",
          "This is a short description",
          "This is a description",
          ProjectStatus.LAUFEND,
          "This is a requirement",
          UUID.randomUUID(),
          "Mock User",
          "Supervisor",
          ProjectContext.PROFESSOR);

  @BeforeEach
  void setUp() {
    when(auditorAware.getCurrentAuditor()).thenReturn(Optional.of(USER_ID));
  }

  // GET /projects/{id}
  @Test
  void when_get_to_projects_id_then_is_ok() throws Exception {
    projectRepository.save(sampleProject);

    mockMvc
        .perform(get(PROJECTS_ID_ROUTE, sampleProject.getId()))
        .andDo(print())
        .andExpect(status().isOk());
  }

  // GET /projects
  @Test
  void when_get_to_projects_then_is_ok() throws Exception {
    var res = projectRepository.save(sampleProject);
    var all = projectRepository.findAll();

    mockMvc.perform(get(PROJECTS_ROUTE)).andDo(print()).andExpect(status().isOk());
  }

  // POST /projects
  @Test
  void when_valid_post_to_projects_then_project_is_saved() throws Exception {
    // Set other non-matching context, in order to check whether it was set correctly
    sampleProject.setContext(ProjectContext.COMPANY);

    mockMvc
        .perform(
            post(PROJECTS_ROUTE)
                .contentType(MediaType.APPLICATION_JSON)
                .content(new ObjectMapper().writeValueAsString(sampleProject)))
        .andDo(print())
        .andExpect(status().isCreated());

    Optional<Project> foundProject = projectRepository.findById(sampleProject.getId());

    // Set matching context
    sampleProject.setContext(ProjectContext.PROFESSOR);

    assertTrue(foundProject.isPresent());
    assertEquals(sampleProject, foundProject.get());
  }

  // DELETE /projects/{id}
  @Test
  void when_delete_to_projects_id_then_project_is_deleted() throws Exception {
    projectRepository.save(sampleProject);

    mockMvc
        .perform(delete(PROJECTS_ID_ROUTE, sampleProject.getId()))
        .andDo(print())
        .andExpect(status().isNoContent());

    Optional<Project> foundProject = projectRepository.findById(sampleProject.getId());

    assertFalse(foundProject.isPresent());
  }

  // PUT /projects/{id}
  @Test
  void when_put_to_projects_id_then_project_is_updated() throws Exception {
    projectRepository.save(sampleProject);

    Project copiedProject = sampleProject;
    copiedProject.setDescription("Updated");

    mockMvc
        .perform(
            put(PROJECTS_ID_ROUTE, copiedProject.getId())
                .contentType(MediaType.APPLICATION_JSON)
                .content(new ObjectMapper().writeValueAsString(copiedProject)))
        .andDo(print())
        .andExpect(status().isNoContent());

    Optional<Project> foundProject = projectRepository.findById(copiedProject.getId());

    assertTrue(foundProject.isPresent());
    assertEquals(copiedProject, foundProject.get());
  }

  // PUT /projects/{id}
  @Test
  void when_put_to_projects_id_then_project_is_created() throws Exception {
    mockMvc
        .perform(
            put(PROJECTS_ID_ROUTE, sampleProject.getId())
                .contentType(MediaType.APPLICATION_JSON)
                .content(new ObjectMapper().writeValueAsString(sampleProject)))
        .andDo(print())
        .andExpect(status().isCreated());

    Optional<Project> foundProject = projectRepository.findById(sampleProject.getId());

    assertTrue(foundProject.isPresent());
    assertEquals(sampleProject, foundProject.get());
  }

  // PATCH /projects/{id}
  @Test
  void when_patch_to_projects_id_then_project_is_updated() throws Exception {
    projectRepository.save(sampleProject);

    Project copiedProject = sampleProject;
    copiedProject.setDescription("Updated");

    mockMvc
        .perform(
            patch(PROJECTS_ID_ROUTE, sampleProject.getId())
                .contentType(MediaType.APPLICATION_JSON)
                .content(new ObjectMapper().writeValueAsString(copiedProject)))
        .andDo(print())
        .andExpect(status().isNoContent());

    Optional<Project> foundProject = projectRepository.findById(sampleProject.getId());

    assertTrue(foundProject.isPresent());
    assertEquals(copiedProject, foundProject.get());
  }
}
