eureka:
  client:
    enabled: false
moduleImport:
  delay:
    initial:
      seconds: 0
spring:
  datasource:
    password: project-service
    url: jdbc:postgresql://localhost:5432/project-db
    username: project-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true