eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
keycloak:
  auth-server-url: https://login.aws.innovation-hub.de/auth
  bearer-only: true
  cors: false
  realm: innovation-hub-bergisches-rheinland
  resource: prox-project-service
server:
  port: 9002
  forward-headers-strategy: native
spring:
  application:
    name: project-service
  data:
    rest:
      max-page-size: 1000000000
      default-page-size: 1000000000
  datasource:
    password: project-service
    url: jdbc:postgresql://project-db:5432/project-db
    username: project-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
