server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: project-service
  data:
    rest:
      max-page-size: 1000000000
      default-page-size: 1000000000
  datasource:
    password: project-service
    url: jdbc:postgresql://project-db:5432/project-db
    username: project-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.aws.innovation-hub.de/auth/realms/innovation-hub-bergisches-rheinland
