eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
moduleImport:
  delay:
    initial:
      seconds: 0
spring:
  datasource:
    password: project-service
    url: jdbc:h2:mem:testdb
    username: project-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
keycloak:
  auth-server-url: http://127.0.0.1:8080/auth