{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prox-project-service.fullname" . }}
  labels:
    {{- include "prox-project-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    moduleImport:
      delay:
        initial:
          seconds: 10
        hasData:
          minutes: 1440
        hasNoData:
          seconds: 10
    tagServiceLink:
      port: 9003
      tag-collection: tagCollections
    professorServiceLink:
      port: 9005
      professor-resource: professors
    keycloak:
      auth-server-url: https://login.aws.innovation-hub.de/auth
      bearer-only: true
      cors: false
      principal-attribute: preferred_username
      realm: archilab
      resource: prox-project-service
    server:
      port: 8080
      forward-headers-strategy: native
    spring:
      application:
        name: project-service
      data:
        rest:
          max-page-size: 1000000000
          default-page-size: 1000000000
      datasource:
        url: jdbc:postgresql://prox-project-service-db:5432/postgres
        username: postgres
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            jdbc:
              lob:
                non_contextual_creation: true
  {{- end }}
