version: "3.7"

services:

  project-service:
    image: ${REPOSITORY}/${IMAGE}:${TAG}

  project-db:
    image: postgres:11.3-alpine
    volumes:
      - project-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=project-service
      - POSTGRES_PASSWORD=project-service
      - POSTGRES_DB=project-db
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  project-db-data: